// Task-domain schemas. All task identifiers are UUID v4 strings generated by
// the gateway. Status/priority enums mirror the DB constraints in
// sdk/db/migrations/001_initial_schema.sql so that a schema-level parse()
// catches invalid states before they reach SQLite.
//
// Phase 1 — lifted from shared/schemas/task.js.
// Phase 5 — expanded to add `orphaned` state, V2 submit / request_verification
// contracts, claim-orphan, and the journal enforcement shapes. Journal schemas
// live in this file (instead of a separate core/schemas/journal.js) so the
// tasks plane has a single extensible import.
import { z } from 'zod';

export const TaskStatusSchema = z.enum([
  'pending',
  'claimed',
  'in_progress',
  'submitted',
  'review',
  'approved',
  'rejected',
  'cancelled',
  'failed',
  'orphaned', // Phase 5 — session-reaper target status.
]);

export const TaskPrioritySchema = z.enum(['low', 'medium', 'normal', 'high', 'critical']);

export const TaskCreateSchema = z.object({
  // project_id is validated against the projects table at the handler
  // boundary (404 if missing). The format is conventionally a UUID but
  // contract-test fixtures use short identifiers ('proj-1' etc.); enforcing
  // UUID at the schema layer would break those without adding a real
  // validation guarantee — the row-existence check is authoritative.
  project_id: z.string().min(1),
  title: z.string().min(1).max(200),
  // Description is optional in the data model — many fixture / quick-create
  // paths leave it empty. Title is the required human-facing field.
  description: z.string().optional(),
  phase_number: z.number().int().positive().optional(),
  priority: TaskPrioritySchema.optional(),
  tags: z.array(z.string()).max(16).optional(),
  // section — the task's style/category (e.g. "MCP & Tools"). Stored inside
  // the metadata JSON blob (no dedicated column); createTask copies it across
  // when present. Optional so pre-section callers and quick-create paths are
  // unaffected.
  section: z.string().max(100).regex(/^[^\n\r]*$/, 'section must be single-line').optional(),
});

// Retained as the V1 surface for bot callers that still pass {task_id,
// reviewer, summary?}. V2 below is what state-machine.requestVerification
// validates against.
export const RequestVerificationSchema = z.object({
  task_id: z.string().min(1),
  reviewer: z.string().min(1),
  summary: z.string().optional(),
});

// --- Phase 5: task admin + lifecycle schemas ---------------------------------

export const TaskUpdateSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  description: z.string().max(5000).optional(),
  priority: TaskPrioritySchema.optional(),
  tags: z.array(z.string()).max(16).optional(),
  // section — updateTask (transitions.js) treats `undefined` as "leave it"
  // and `null` as "clear the bucket so the dashboard falls back to General".
  // Must be nullable so that explicit-null clear path actually reaches the
  // handler; plain .optional() would strip null and leave the clear dead.
  section: z.string().max(100).regex(/^[^\n\r]*$/, 'section must be single-line').nullable().optional(),
});

export const TaskCancelSchema = z.object({
  reason: z.string().min(1).max(1000),
});

// Added to unblock transitions.js barrel load (Phase 3.0.b).
// Mirrors TaskCancelSchema — both require a reason string.
export const TaskFailSchema = z.object({
  reason: z.string().min(1).max(1000),
});

// No specific fields required from the caller — the handler only checks
// ownership/authz then mutates metadata. passthrough() preserves any
// extra fields without rejecting the body.
export const TaskDeleteRequestSchema = z.object({}).passthrough();

export const TaskReleaseSchema = z.object({
  reason: z.string().max(1000).optional(),
  force: z.boolean().optional(),
});

// Callers send `new_agent` or the legacy `agent_id`; the state-machine reads
// whichever is present. A refine() keeps the "at least one" guarantee at the
// schema layer so handlers never have to recheck.
export const TaskReassignSchema = z.object({
  new_agent: z.string().min(1).max(100).optional(),
  agent_id: z.string().min(1).max(100).optional(),
}).refine((v) => v.new_agent || v.agent_id, { message: 'new_agent or agent_id required' });

export const TaskReopenSchema = z.object({
  reason: z.string().min(1).max(1000),
});

export const TaskCommentSchema = z.object({
  comment: z.string().min(1).max(2000),
});

// V2 — submit_result. `task_id` is part of the schema so HTTP and MCP callers
// go through one safeParse (no ad-hoc null-check guards in the handler).
// Journal completeness is enforced at handler runtime, not at the schema
// layer (zod can't query a DB).
export const SubmitResultSchemaV2 = z.object({
  task_id: z.string().min(1),
  summary: z.string().min(1).max(5000),
  files_changed: z.array(z.string()).max(1024).optional(),
  override_stub_check: z.boolean().optional(),
});

// V2 — request_verification. `reviewer` preferred; `reviewer_agent` is
// accepted as a back-compat alias from the legacy protocol.
export const RequestVerificationSchemaV2 = z.object({
  task_id: z.string().min(1),
  reviewer: z.string().min(1).max(100).optional(),
  reviewer_agent: z.string().min(1).max(100).optional(),
  summary: z.string().max(5000).optional(),
});

// NEW — adopting an orphaned task. The only input is a courtesy ack; the
// handler wires journal inheritance regardless.
export const TaskClaimOrphanSchema = z.object({
  acknowledge_previous_work: z.boolean().optional(),
});

// --- Phase 5: journal schemas ------------------------------------------------
//
// The journal is the authoritative "did the agent think through this task"
// signal consulted by submitTask + requestVerification. Entry types are a
// closed enum; summary is required (blank entries don't count toward
// completeness).
export const JournalEntryTypeSchema = z.enum([
  'planning', 'context', 'decision', 'test', 'blocker', 'handoff',
]);

/**
 * The three entry types submit_result demands. request_verification in
 * `strict_verification` mode additionally requires `decision` + `test`
 * (handled in the journal helper, not here).
 */
export const REQUIRED_ENTRY_TYPES = Object.freeze(['planning', 'context', 'test']);

export const JournalEntrySchema = z.object({
  id: z.string().min(1),
  task_id: z.string().min(1),
  entry_type: JournalEntryTypeSchema,
  summary: z.string().min(1).max(5000),
  files_changed: z.array(z.string()).max(1024).optional(),
  metadata: z.record(z.unknown()).optional(),
  author: z.string().min(1).max(100),
  created_at: z.number().int().nonnegative().optional(),
});

// Body shape for POST /v1/api/tasks/:id/journal. `task_id` is injected from
// the URL in the handler; callers never send it.
export const JournalAppendSchema = z.object({
  entry_type: JournalEntryTypeSchema,
  summary: z.string().min(1).max(5000),
  files_changed: z.array(z.string()).max(1024).optional(),
  metadata: z.record(z.unknown()).optional(),
});

// GET /v1/api/tasks/:id/journal query params. `coerce` lets the adapter pass
// raw URLSearchParams values (strings) directly.
export const JournalQuerySchema = z.object({
  entry_type: JournalEntryTypeSchema.optional(),
  limit: z.coerce.number().int().min(1).max(500).optional(),
});
