// Task-domain schemas. All task identifiers are UUID v4 strings generated by
// the gateway. Status/priority enums mirror the DB check constraints in
// services/gateway/lib/db.js so that a schema-level parse() catches invalid
// states before they reach SQLite.
import { z } from 'zod';

export const TaskStatusSchema = z.enum([
  'pending',
  'claimed',
  'in_progress',
  'submitted',
  'review',
  'approved',
  'rejected',
  'cancelled',
  'failed',
]);

export const TaskPrioritySchema = z.enum(['low', 'medium', 'normal', 'high', 'critical']);

export const TaskCreateSchema = z.object({
  // project_id is validated against the projects table at the handler
  // boundary (404 if missing). The format is conventionally a UUID but
  // contract-test fixtures use short identifiers ('proj-1' etc.); enforcing
  // UUID at the schema layer would break those without adding a real
  // validation guarantee — the row-existence check is authoritative.
  project_id: z.string().min(1),
  title: z.string().min(1).max(200),
  // Description is optional in the data model — many fixture / quick-create
  // paths leave it empty. Title is the required human-facing field.
  description: z.string().optional(),
  phase_number: z.number().int().positive().optional(),
  priority: TaskPrioritySchema.optional(),
  tags: z.array(z.string()).max(16).optional(),
  section: z.string().max(100).optional(),
});

export const RequestVerificationSchema = z.object({
  task_id: z.string().min(1),
  reviewer: z.string().min(1),
  summary: z.string().optional(),
});
